version: 0.0
os: linux

files:
  - source: /target/adl-apps-nmns-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/adl-apps-nmns
    overwrite: true  # 明確指定覆蓋現有檔案
  - source: /scripts
    destination: /home/ec2-user/adl-apps-nmns/scripts
    overwrite: true  # 明確指定覆蓋現有檔案

permissions:
  - object: /home/ec2-user/adl-apps-nmns
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/adl-apps-nmns/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
  - object: /home/ec2-user/adl-apps-nmns
    pattern: "*.jar"
    owner: ec2-user
    group: ec2-user
    mode: 644
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ec2-user